SuperAdmin/tg-8/create-get
BaSP-a2022/capi-a-trackgenix-server pull request #12
Opened 2022-10-17 12:00 UTC by Maxi-SR

Get all super admins, get super admin by id and create a super admin. 
Note: I'm working on port 3000 because I'm having problems with 5000, be careful with that.

2022-10-17 12:46 UTC, martinraveglia requested changes
The name of this PR is not OK, it should be `BaSP-TG-XX: Short description`
The name of the branch is not ok either, it should have been `feature/TG-8/create-get-superAdmins`. Don't change it now, as it's not simple. But take that I mind.

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    });
Please change this error handling with what is proposed in the weekly problem.

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +  }
Please change this error handling with what is proposed in the weekly problem.

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    });
This endpoint is to get a superAdmin by ID. We should update the naming here to reflect that. (Is not to get an admin, but a superAdmin)

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    });
If there is no admin found with given id, what is the result? It should respond with a 404 error

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    return res.json({
we're not setting the error response code here

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    return res.json({
we're not setting the error response code here

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +// import express from 'express';
Why is this whole file commented?

2022-10-17 12:46 UTC, martinraveglia commented on src/index.js
> +const port = process.env.PORT || 5000;
Please leave this on port 3000, change it In your PC if needed, but don't push those changes

2022-10-17 12:46 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +
please remove this line break

2022-10-17 12:46 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +
please remove this line break

2022-10-17 12:46 UTC, martinraveglia commented on src/routes/superAdmins.js
> +  .put('/:id');
Please, update how this is defined, do it as follows to keep the code understandable and more tidy,

```
router.get('/', superAdminsController.getAllSuperAdmins)

router.get('/:id', superAdminsController.getAdminById)

router.post('/', superAdminsValidation.validateCreation, superAdminsController.createSuperAdmin)

router.delete('/:id')

router.put('/:id');
```

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +};
Let's export this with no `default`, as 
```
export {
  getAllSuperAdmins,
  getAdminById,
  createSuperAdmin,
};
```

2022-10-17 12:46 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +  }
Please change this error handling with what is proposed in the weekly problem.

2022-10-17 12:46 UTC, martinraveglia commented on src/validations/superAdmins.js
> +};
Let's export this with no `default`

2022-10-17 12:46 UTC, martinraveglia commented on src/routes/superAdmins.js
> +import superAdminsValidation from '../validations/superAdmins';
After changing exports on those files, import them method by method, as 
```
import { validateCreation } from '../validations/superAdmins';
```

2022-10-17 12:46 UTC, martinraveglia commented on postman_collection.json
> +            "raw": "localhost:5000/superAdmins/:id",
Let's keep this on port 3000, change it in your PC if needed, but do not push those port changes

2022-10-17 12:46 UTC, martinraveglia commented on postman_collection.json
> +            "raw": "localhost:5000/superAdmins/",
Let's keep this on port 3000, change it in your PC if needed, but do not push those port changes

2022-10-17 12:46 UTC, martinraveglia commented on postman_collection.json
> +            "raw": "localhost:5000/superAdmins/",
Let's keep this on port 3000, change it in your PC if needed, but do not push those port changes

2022-10-17 20:22 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +    });
The 404 error has to be in the catch, right?

2022-10-17 20:43 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +    });
`const getSuperAdminById = async (req, res) => {
  const idSuperAdmin = req.params.id;
  try {
    const superAdmin = await SuperAdmins.findById(idSuperAdmin);
    console.log(superAdmin);
    return res.status(200).json({
      message: `Admin with id: ${idSuperAdmin} found`,
      data: superAdmin,
      error: false,
    });
  } catch (error) {
    return res.status(404).json({
      message: 'An error ocurred',
      error,
    });
  }
};`

2022-10-17 20:48 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +    });
Like this? 

`const getSuperAdminById = async (req, res) => {
  const idSuperAdmin = req.params.id;
  try {
    const superAdmin = await SuperAdmins.findById(idSuperAdmin);
    console.log(superAdmin);
    return res.status(200).json({
      message: `Super admin with id: ${idSuperAdmin} found`,
      data: superAdmin,
      error: false,
    });
  } catch (error) {
    return res.status(404).json({
      message: `Super admin with id: ${idSuperAdmin} not exist`,
      error,
    });
  }
};`

2022-10-17 20:53 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +  }
`} catch (error) {
    return res.status(400).json({
      message: 'An error ocurred',
      error,
    });
  }
};`

2022-10-17 21:01 UTC, Maxi-SR commented on src/controllers/timeSheets.js
> +// import express from 'express';
Do I have to delete all from this file?

2022-10-17 21:04 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +    });
> The name of this PR is not OK, it should be `BaSP-TG-XX: Short description` The name of the branch is not ok either, it should have been `feature/TG-8/create-get-superAdmins`. Don't change it now, as it's not simple. But take that I mind.

I thought it was implied in the feature, sorry for that.

2022-10-17 21:33 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +  }
I do not understand what I've to change here? Status code?

2022-10-17 21:34 UTC, Maxi-SR commented on src/controllers/superAdmins.js
> +    return res.json({
Is this the same comment as above?

2022-10-17 22:08 UTC, martinraveglia requested changes

2022-10-17 22:08 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    });
No, as proposed in the weekly exercise.
```
return res.status(404).json({
    message: error, // error.toString()
    data: undefined,
    error: true
});
```

Let's try and define if is better to put `error` or `error.toString()`

2022-10-17 22:08 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    return res.json({
no, we need to set the statusCode to a 400 or 404 code on every error responses, in this case it should be a 404 code.

2022-10-17 22:08 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +  }
No, as proposed in the weekly exercise.

```
return res.status(404).json({
    message: error, // error.toString()
    data: undefined,
    error: true
});
```

Let's try and define if is better to put error or error.toString()

2022-10-17 22:08 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +  }
```
return res.status(400).json({
    message: error, // error.toString()
    data: undefined,
    error: true
});
```

2022-10-17 22:08 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +// import express from 'express';
No, we should let it uncommented as it was originally, the teammate who needs to work on the timeSheets related methods will handle this file

2022-10-19 15:50 UTC, martinraveglia requested changes

2022-10-19 15:50 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    if (error.message.includes('Super admin with')) {
This will never match the error

2022-10-19 15:50 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    return res.status(404).json({
this error should not be a 404

2022-10-19 15:50 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +const superAdminSchema = new Schema({
A lineBreak is necessary here in between line 3 and 4

2022-10-19 15:50 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +export default mongoose.model('SuperAdmin', superAdminSchema);
A lineBreak is necessary here in between line 9 and 10

2022-10-19 22:00 UTC, martinraveglia requested changes

2022-10-19 22:00 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    return res.status(404).json({
statusCode should be 404 only if no superAdmin was found with the given Id, it should be 400 otherwise

2022-10-19 22:44 UTC, martinraveglia requested changes

2022-10-19 22:44 UTC, martinraveglia commented on src/index.js
> +app.use('/superAdmins', superAdminRoute);
This belongs to the routes index file!!

2022-10-19 23:00 UTC, Maxi-SR commented on src/index.js
> +app.use('/superAdmins', superAdminRoute);
I think I got it right, I'm not sure but it works

2022-10-20 02:48 UTC, martinraveglia requested changes

2022-10-20 02:48 UTC, martinraveglia commented on src/index.js
> +import router from './routes/index';
this should be named routes (as in the original file)

2022-10-20 02:48 UTC, martinraveglia commented on src/validations/superAdmins.js
> +  const validation = superAdminValidation.validateAsync(req.body, { abortEarly: false });
why are you using validateAsync? This calls for an asynchronous method that you're not handling and therefore the app crashes when validation is not successful. Let's use `.validate` instead as it is synchronous.

2022-10-20 02:48 UTC, martinraveglia commented on src/validations/superAdmins.js
> +    });
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-20 23:49 UTC, martinraveglia requested changes

2022-10-20 23:49 UTC, martinraveglia commented on src/index.js
> +import routes from './routes/index';
```suggestion
import routes from './routes';
```

2022-10-21 00:25 UTC, martinraveglia requested changes

2022-10-21 00:25 UTC, martinraveglia commented on src/routes/index.js
>  // import admins from './admins';
please delete this line

2022-10-21 00:25 UTC, martinraveglia commented on src/routes/index.js
>  // router.use('/admins', admins);
please delete this line

2022-10-21 00:35 UTC, martinraveglia approved these changes

2022-10-21 00:35 UTC, merged