BaSP-TG-10: Create and get Tasks.
BaSP-a2022/capi-a-trackgenix-server pull request #13
Opened 2022-10-18 02:26 UTC by EliasBermudez13

Add a new task to the MongoDB database using Joi validations and Mongoose Schema.
Get all the tasks from the database. Get only one finded by its "id".

2022-10-19 16:11 UTC, martinraveglia requested changes

2022-10-19 16:11 UTC, martinraveglia commented on src/controllers/tasks.js
> +      hours: req.body.hours,
this is not as the data model that was provided to the team. Update it taking into account that data model

2022-10-19 16:11 UTC, martinraveglia commented on src/models/Tasks.js
> +  hours: { type: Number, required: true },
this is not as the data model that was provided to the team. Update it taking into account that data model

2022-10-19 16:11 UTC, martinraveglia commented on src/validations/tasks.js
> +    hours: Joi.number().required(),
this is not as the data model that was provided to the team. Update it taking into account that data model

2022-10-19 16:11 UTC, martinraveglia commented on src/validations/tasks.js
> +};
if we are exporting this with default, there is no need to export it as an object. Export the plain method instead
```suggestion
export default validateCreation;
```

2022-10-19 19:32 UTC, EliasBermudez13 commented on src/controllers/tasks.js
> +      hours: req.body.hours,
I'm sorry i don't get it, can you explain yourself a little more? Thanks

2022-10-19 22:44 UTC, martinraveglia requested changes

2022-10-19 22:44 UTC, martinraveglia commented on src/index.js
> +app.use('/tasks', taskRoutes);
This belongs to the routes index file!!

2022-10-19 22:49 UTC, EliasBermudez13 commented on src/index.js
> +app.use('/tasks', taskRoutes);
Like that ? : app.use (taskRoutes);

2022-10-19 22:50 UTC, EliasBermudez13 commented on src/index.js
> +app.use('/tasks', taskRoutes);
Or i left only app.use(routes)

2022-10-19 22:55 UTC, martinraveglia commented on src/index.js
> +app.use('/tasks', taskRoutes);
you should let app.use(routes) here in this file, take a look at the routes index.js to understand why

2022-10-19 23:01 UTC, EliasBermudez13 commented on src/index.js
> +app.use('/tasks', taskRoutes);
okay, thanks

2022-10-20 02:53 UTC, martinraveglia requested changes

2022-10-20 02:53 UTC, martinraveglia commented on src/index.js
> +import routes from './routes/index';
this file should be unmodified, originally this line was imported as,
```suggestion
import routes from './routes';
```

2022-10-20 02:57 UTC, martinraveglia requested changes

2022-10-20 02:57 UTC, martinraveglia commented on postman_collection.json
> +							"raw": "{\r\n    \"name\": \"Task3\",\r\n    \"description\": \"One more task descritpion for test purposes\",\r\n    \"project_id\": \"634de88a9a45e5e780e62787\",\r\n    \"hours\": 1\r\n}   "
this body data is not updated, more data than necessary is being sent

2022-10-20 23:50 UTC, martinraveglia approved these changes

2022-10-21 00:45 UTC, martinraveglia requested changes

2022-10-21 00:45 UTC, martinraveglia commented on src/routes/tasks.js
> +import {validateCreation, validateEdit} from '../validations/tasks';
```suggestion
import { validateCreation, validateEdit } from '../validations/tasks';
```

2022-10-21 00:45 UTC, martinraveglia commented on src/validations/tasks.js
> +};
```suggestion
export { 
 validateCreation,
 validateEdit 
};
```

2022-10-21 00:53 UTC, martinraveglia approved these changes

2022-10-21 00:53 UTC, merged