BaSP-TG-11: Delete and Update a Task.
BaSP-a2022/capi-a-trackgenix-server pull request #14
Opened 2022-10-18 04:07 UTC by EliasBermudez13

Delete a task by its id, and update too, using Joi validation.

2022-10-19 21:59 UTC, martinraveglia requested changes

2022-10-19 21:59 UTC, martinraveglia commented on src/controllers/tasks.js
> +      message: error,
let's change this to error.toString()

2022-10-19 21:59 UTC, martinraveglia commented on src/controllers/tasks.js
> +    return res.status(404).json({
statusCode should be 404 only if no task was found with the given Id, it should be 400 otherwise

2022-10-19 21:59 UTC, martinraveglia commented on src/controllers/tasks.js
> +    return res.status(400).json({
If no task with the id given was found, the status code should be 404

2022-10-19 21:59 UTC, martinraveglia commented on src/controllers/tasks.js
> +      { ...req.body },
why are you destructuring this like that? It's the same as passing just `req.body`

2022-10-19 21:59 UTC, martinraveglia commented on src/index.js
> +app.use('/tasks/', taskRoutes);
```suggestion
app.use('/tasks', taskRoutes);
```

2022-10-19 21:59 UTC, martinraveglia commented on src/models/Tasks.js
> +  hours: { type: Number, required: true },
this is not as the data model that was provided to the team. Update it taking into account that data model

2022-10-19 21:59 UTC, martinraveglia commented on src/validations/tasks.js
> +const validateCreation = (req, res, next) => {
We're not using this validation on this PR, why is it included?

2022-10-19 21:59 UTC, martinraveglia commented on src/controllers/tasks.js
> +      message: error,
Let's change this to error.toString()

2022-10-19 22:02 UTC, EliasBermudez13 commented on src/controllers/tasks.js
> +      { ...req.body },
Like const result = await Tasks.findByIdAndUpdate({req.body}) ?

2022-10-19 22:32 UTC, martinraveglia commented on src/controllers/tasks.js
> +      { ...req.body },
So close haha, let's do 
```
const result = await Tasks.findByIdAndUpdate(
      { _id: id },
      req.body,
      { new: true },
    );
```

2022-10-19 22:45 UTC, martinraveglia requested changes

2022-10-19 22:45 UTC, martinraveglia commented on src/index.js
> +app.use('/tasks/', taskRoutes);
This belongs to the routes index file!!

2022-10-20 03:01 UTC, martinraveglia requested changes
The postman collection was not updated

2022-10-20 03:25 UTC, martinraveglia approved these changes

2022-10-20 03:25 UTC, merged