BaSP-TG-09: delete and update a super admin
BaSP-a2022/capi-a-trackgenix-server pull request #16
Opened 2022-10-19 00:52 UTC by Maxi-SR

Feature to delete a super admin by id and update it too.

2022-10-19 22:28 UTC, martinraveglia requested changes

2022-10-19 22:28 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +});
A lineBreak is necessary here in between line 9 and 10

2022-10-19 22:28 UTC, martinraveglia commented on src/models/SuperAdmins.js
> +const superAdminSchema = new Schema({
A lineBreak is necessary here in between line 3 and 4

2022-10-19 22:28 UTC, martinraveglia commented on src/routes/superAdmins.js
> +router.post('/', validateCreation, createSuperAdmin);
Why are these methods here, if this PR is of delete and update features?

2022-10-19 22:28 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +const createSuperAdmin = async (req, res) => {
Why is this method here, if this PR is of delete and update features?

2022-10-19 22:28 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +const getSuperAdminById = async (req, res) => {
Why is this method here, if this PR is of delete and update features?

2022-10-19 22:28 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +const getAllSuperAdmins = async (req, res) => {
Why is this method here, if this PR is of delete and update features?

2022-10-19 22:28 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +const deleteSuperAdmin = async (req, res) => {
We have been using async await on every method, let's update this one for consistency purposes

2022-10-19 22:28 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +const updateSuperAdmin = (req, res) => {
We have been using async await on every method, let's update this one for consistency purposes

2022-10-19 22:28 UTC, martinraveglia commented on src/validations/superAdmins.js
> +    email: Joi.string().pattern(new RegExp(pattern)),
Joi has a built-in method to validate emails, let's use that one

2022-10-19 22:28 UTC, martinraveglia commented on src/validations/superAdmins.js
> +      message: `There was an error: ${validation.error.details[0].message}`,
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-19 22:45 UTC, martinraveglia requested changes

2022-10-19 22:45 UTC, martinraveglia commented on src/index.js
> +app.use('/superAdmins', superAdminRoute);
This belongs to the routes index file!!

2022-10-20 22:30 UTC, Maxi-SR commented on src/routes/superAdmins.js
> +router.post('/', validateCreation, createSuperAdmin);
I delete it after check that delete and update works

2022-10-20 23:59 UTC, martinraveglia requested changes

2022-10-20 23:59 UTC, martinraveglia commented on src/index.js
> +import routes from './routes/index';
```suggestion
import routes from './routes';
```

2022-10-21 00:03 UTC, martinraveglia approved these changes

2022-10-21 12:30 UTC, martinraveglia requested changes

2022-10-21 12:30 UTC, martinraveglia commented on src/controllers/superAdmins.js
> +    if (error.message.includes('Super admin not found')) {
This will never match the error

2022-10-21 12:46 UTC, martinraveglia approved these changes

2022-10-21 12:46 UTC, merged