BaSP-TG-03: Delete and update employees
BaSP-a2022/capi-a-trackgenix-server pull request #19
Opened 2022-10-19 01:10 UTC by ZGMauri

Methods to delete and update employees

2022-10-19 22:51 UTC, martinraveglia requested changes

2022-10-19 22:51 UTC, martinraveglia commented on src/controllers/employees.js
> +    return res.status(400).json({
If no employee with the id given was found, the status code should be 404

2022-10-19 22:51 UTC, martinraveglia commented on src/controllers/employees.js
> +      { ...req.body },
why are you destructuring this like that? It's the same as passing just `req.body`

2022-10-19 22:51 UTC, martinraveglia commented on src/controllers/employees.js
> +    return res.status(400).json({
If no employee with the id given was found, the status code should be 404

2022-10-19 22:51 UTC, martinraveglia commented on src/controllers/timeSheets.js
> -import express from 'express';
Why did you erase this file content? It should remain untouched as your feature is not related to timeSheets

2022-10-19 22:51 UTC, martinraveglia commented on src/validations/employees.js
> +    });
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-19 22:51 UTC, martinraveglia commented on src/validations/employees.js
> +};
We are exporting only one method, exporting it as an object is not necessary

2022-10-21 00:07 UTC, martinraveglia requested changes

2022-10-21 00:07 UTC, martinraveglia commented on src/controllers/employees.js
> +    if (error.message.includes('Employee not found')) {
this will never match the error

2022-10-21 00:07 UTC, martinraveglia commented on src/controllers/employees.js
> +    if (error.message.includes('Employee not found')) {
This will never match the error

2022-10-21 00:07 UTC, martinraveglia commented on src/routes/employees.js
> +router.put('/:id', employeesValidations.validateUpdate, updateEmployees);
this is wrongly used now

2022-10-21 00:10 UTC, ZGMauri commented on src/routes/employees.js
> +router.put('/:id', employeesValidations.validateUpdate, updateEmployees);
yes I saw this error while correcting the other PR

2022-10-21 01:37 UTC, martinraveglia requested changes

2022-10-21 01:37 UTC, martinraveglia commented on src/controllers/employees.js
> +      status = 404;
Status is always 404 with this logic, also, the error message will never match. Please try to understand how this logic works!

```suggestion
    let status = 400;
    if (error.message.includes('Employee with id')) {
      status = 404;
```

2022-10-21 01:37 UTC, martinraveglia commented on src/controllers/employees.js
> +    if (!error.message.includes('Employee not found')) {
The error message will never match. Please try to understand how this logic works!

```suggestion
    if (!error.message.includes(`Employee ${req.query.id} not found`)) {
```

2022-10-21 22:29 UTC, martinraveglia approved these changes

2022-10-21 22:29 UTC, merged