Employee/tg/create and edit
BaSP-a2022/capi-a-trackgenix-server pull request #2
Opened 2022-10-11 19:43 UTC by eialyafe

2022-10-11 20:55 UTC, martinraveglia requested changes

2022-10-11 20:55 UTC, martinraveglia commented on src/resources/employees.js
> +router.post('/createEmployee', (req, res) => {
The full route to this endpoint is `/employees/createEmployee`, this seems redundant and it would be better to call this endpoint `/employees/create`. 
```suggestion
router.post('/create', (req, res) => {
```

2022-10-11 20:55 UTC, martinraveglia commented on src/resources/employees.js
> +router.put('/editEmployee', (req, res) => {
The same comment applies here, let's change this path to `/edit`

2022-10-11 20:55 UTC, martinraveglia commented on src/index.js
> +app.use('/employee', employeeRouter);
let's put this prefix in plural
```suggestion
app.use('/employees', employeeRouter);
```

2022-10-11 20:55 UTC, martinraveglia commented on src/resources/employees.js
> +const express = require('express');
this should be imported with `import...from`, EVERY library should be imported with that sentence, only .json files should be imported with required

```suggestion
import express from 'express';
```

2022-10-11 20:55 UTC, martinraveglia commented on src/resources/employees.js
> +const fs = require('fs');
Same comment about the import statement here, all the imports should be grouped together at the top of the document

2022-10-11 21:02 UTC, martinraveglia requested changes

2022-10-11 21:02 UTC, martinraveglia commented on src/resources/employees.js
> +  newEmployeesList = newEmployeesList.map((employee) => {
The assignment newEmployeesList = employees is not necessary here, we can change this piece of code to,
```suggestion
  const newEmployeesList = employees.map((employee) => {
```

2022-10-12 02:26 UTC, martinraveglia submitted a review, later dismissed

2022-10-13 00:55 UTC, eialyafe commented
Functionalities to crating and edition employee

2022-10-13 17:06 UTC, martinraveglia requested changes

2022-10-13 17:06 UTC, martinraveglia commented on src/index.js
> +// eslint-disable-next-line import/no-named-as-default, import/no-named-as-default-member
Delete this eslint rule overwrite, we should never solve lint issues this way, because we are not solving the issue itself but bypassing it.

2022-10-13 17:06 UTC, martinraveglia commented on src/index.js
> +  // eslint-disable-next-line no-console
Remove this eslint rule overwrite

2022-10-13 17:06 UTC, martinraveglia commented on src/resources/employees.js
> +export default router;
This should be positioned at the end of the file

2022-10-13 17:06 UTC, martinraveglia commented on src/resources/employees.js
> +  const employee = require('../data/employees.json');
This was already imported at the beginning of the file

2022-10-13 17:14 UTC, martinraveglia requested changes

2022-10-13 17:14 UTC, martinraveglia commented on src/index.js
> +app.use('/employees', employeeRouter);
Please remove this line as it is the same that what's on line 17

2022-10-13 17:54 UTC, martinraveglia approved these changes

2022-10-13 17:54 UTC, merged