BaSP-TG-06: Get and create projects
BaSP-a2022/capi-a-trackgenix-server pull request #20
Opened 2022-10-19 01:18 UTC by camilavaleriarojas

Get all employees, get by Id, get by filters and create new project.

2022-10-19 23:11 UTC, martinraveglia requested changes

2022-10-19 23:11 UTC, martinraveglia commented on src/controllers/projects.js
> +    return res.status(404).json({
statusCode should be 404 only if no project was found with the given Id, it should be 400 otherwise

2022-10-19 23:11 UTC, martinraveglia commented on src/validations/projects.js
> +  }
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-19 23:11 UTC, martinraveglia commented on src/validations/projects.js
> +};
We are exporting only one method, exporting it as an object is not necessary

2022-10-20 03:16 UTC, martinraveglia requested changes

2022-10-20 03:16 UTC, martinraveglia commented on src/controllers/projects.js
> +    if (error.message.includes('Project not found.')) {
this will never match, as the thrown error has no '.' at the end

2022-10-20 03:16 UTC, martinraveglia commented on src/controllers/projects.js
> +    if (error.message.includes('Project not found.')) {
this will never match, as the thrown error has no '.' at the end

2022-10-20 03:16 UTC, martinraveglia commented on src/models/Projects.js
> +    }],
let's break this into two lines, as follows,
```suggestion
    }
  ],
```

2022-10-20 03:16 UTC, martinraveglia commented on src/routes/projects.js
> +router.post('/', projectsValidations.validateCreation, createProject);
this is wrongly called now (`projectsValidations.validateCreation`), as we've changed how the validation is exported from the validations' file

2022-10-20 03:16 UTC, martinraveglia commented on src/validations/projects.js
> +  }
`if we have more than one validation error (in more than one field), all errors should be sent`
This is still unresolved, we need to use a Joi configuration, look for the `abortEarly` property on google !

For example, if we try to create a project with both `name` and `description` missing, the expected result is to receive that both fields are required, not just one of them. 
Right now I'm receiving `"message": "\"description\" is required",`

2022-10-20 05:09 UTC, camilavaleriarojas commented on src/validations/projects.js
> +  }
Applied the property and it worked, thanks for the recommendation

2022-10-20 23:47 UTC, martinraveglia approved these changes

2022-10-21 00:33 UTC, martinraveglia approved these changes

2022-10-21 00:33 UTC, merged