Feature/tg 12/get and get by id time sheets
BaSP-a2022/capi-a-trackgenix-server pull request #22
Opened 2022-10-19 01:32 UTC by eialyafe

Timesheet:  funcionalities: get, getbyid, create, delete and edit

2022-10-19 23:23 UTC, martinraveglia requested changes
The PR title does not follow the format asked

2022-10-19 23:23 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +  }
This should be inside the try...catch statement, otherwise, nothing is 'catching' the error thrown.

Also, if there is no timeSheet in the database, no error should be thrown, but just return a successful response (because there is no timeSheet in the database, no filter error occurred)

You might want to have a look at the video we have on validation from the meeting with your teammates made yesterday

2022-10-19 23:23 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +  const result = await TimeSheets.findById(id);
This should be inside the try...catch statement, otherwise, nothing is 'catching' the error thrown.

2022-10-19 23:23 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +  const result = await TimeSheets.findByIdAndDelete(id);
This should be inside the try...catch statement, otherwise, nothing is 'catching' the error thrown.

2022-10-19 23:23 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +      { ...req.body },
why are you destructuring this like that? It's the same as passing just `req.body`

2022-10-19 23:23 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +    return res.status(400).json({
If no employee with the id given was found, the status code should be 404

2022-10-19 23:23 UTC, martinraveglia commented on src/validations/timesheets.js
> +    });
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-19 23:23 UTC, martinraveglia commented on src/validations/timesheets.js
> +    });
if we have more than one validation error (in more than one field), all errors should be sent

2022-10-20 20:09 UTC, eialyafe commented
All correctiones fixed

2022-10-21 00:15 UTC, martinraveglia requested changes

2022-10-21 00:15 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +    if (error.message.includes('Time sheet not found')) {
this will never match the error

2022-10-21 00:15 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +    if (error.message.includes('Time sheet not found')) {
this will never match the error

2022-10-21 00:15 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +    if (error.message.includes('Time sheet not found')) {
this will never match the error

2022-10-21 00:15 UTC, martinraveglia commented on src/controllers/timeSheets.js
> +    if (error.message.includes('Time sheet not found')) {
this will never match the error

2022-10-21 01:49 UTC, martinraveglia submitted a review, later dismissed

2022-10-21 02:41 UTC, martinraveglia approved these changes

2022-10-21 02:41 UTC, merged