TG: edit a project; add/delete of employees and tasks in projects; assign employees to projects.
BaSP-a2022/capi-a-trackgenix-server pull request #4
Opened 2022-10-11 22:52 UTC by Maxi-SR

2022-10-11 23:27 UTC, martinraveglia requested changes
Please, remove all the comments on the code. The code should be self-explaining and we should avoid adding explanatory comments to it

2022-10-11 23:27 UTC, martinraveglia commented on src/resources/projects.js
> +      const proj = project; // this works because it is passed always by reference in js
this is not necessary, is better to use project as it is declared in the forEach

2022-10-11 23:27 UTC, martinraveglia commented on src/resources/projects.js
> +      proj.project_name = upProject.project_name ? upProject.project_name : project.project_name;
This can be replaced by 
```suggestion
       proj.project_name = upProject.project_name ?? project.project_name;
```

The nullish coalescing operator (??) uses the value of the left side of the expression if the left side of the expression is not null nor undefined, if it is null or undefined the value of the right side of the expression is used.

Same comment applies to the following lines

2022-10-11 23:27 UTC, martinraveglia commented on src/resources/projects.js
> +  });
Here we're only checking if an employee with a role of PM exists already, right? But we should be able to assign employees with roles of PM, DEV, QA, TL. 
Can we update this logic?

In the body we should send something like 
```
{
    "id": "2",
    "name": "maxi schmidt",
    "rol": [
        "DEV"
    ],
    "rate": 80000
}
```

And add the employee if it is not assigned to the project already

2022-10-11 23:33 UTC, Maxi-SR commented on src/resources/projects.js
> +      const proj = project; // this works because it is passed always by reference in js
I have an error with eslint if I don't do that, it tells me no-param-reassing, I talked about it with "Capi" in a meeting and he told me to do something like that

2022-10-12 01:07 UTC, martinraveglia requested changes

2022-10-12 01:07 UTC, martinraveglia commented on src/resources/projects.js
> +// update project
Please remove this comment

2022-10-12 01:07 UTC, martinraveglia commented on src/resources/projects.js
> +      /* edit the name and the start_date of a project */
Please remove this comment

2022-10-12 01:09 UTC, martinraveglia requested changes

2022-10-12 01:09 UTC, martinraveglia commented on src/resources/projects.js
> +      const proj = project; // mandatory
Please remove this comment

2022-10-12 15:54 UTC, martinraveglia requested changes

2022-10-12 15:54 UTC, martinraveglia commented on src/resources/projects.js
> +      const proj = project; // mandatory
This is not resolved!

2022-10-12 15:59 UTC, martinraveglia approved these changes

2022-10-12 15:59 UTC, merged